-- CreateEnum
CREATE TYPE "SportType" AS ENUM ('FOOTBALL', 'BASKETBALL', 'VOLLEYBALL', 'TENNIS', 'HANDBALL', 'TABLETENNIS', 'BADMINTON', 'ESPORTS');

-- AlterTable
ALTER TABLE "teams" ADD COLUMN     "sport" "SportType" NOT NULL DEFAULT 'FOOTBALL';
